# Generated by Django 5.0.6 on 2025-05-18 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SakuraLingo', '0004_chat_group_alter_chat_receiver'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseMatchOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanji', models.TextField()),
                ('answer', models.TextField()),
                ('exercise_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SakuraLingo.exercisematch')),
            ],
        ),
    ]
