# Generated by Django 5.0.6 on 2025-05-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SakuraLingo', '0005_exercisematchoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisematch',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='exercisematch',
            name='kanji',
        ),
    ]
